server:
  port: 8086
spring: 
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java 
      exclude: WEB_INF/**   
  application:
    name: msa-weather-eureka-client-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign: 
  client: 
    config: 
      feignName: 
        connectTimeout: 5000
        readTimeout: 5000
  hystrix: 
    enabled: false
ribbon: 
  eureka:
    enabled: true
zuul:
  routes:
    city: 
      path: /city/**
      service-id: msa-weather-city-eureka
    data: 
      path: /data/**
      service-id: msa-weather-data-eureka