spring: 
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java 
      exclude: WEB_INF/**   
  application:
    name: msa-weather-report-eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign: 
  client: 
    config: 
      feignName: 
        connectTimeout: 5000
        readTimeout: 5000
  hystrix: 
    enabled: false
ribbon: 
  eureka:
    enabled: true